spring.application.name=bank-recon-platform

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/bank_recon}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
